//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPI.Models
{
    using System;
    using System.Configuration;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Encr2014;

    public partial class db_MAILNPPEntities : DbContext
    {
        public db_MAILNPPEntities()
            : base("name=db_MAILNPPEntities")
        {
            var conStr = System.Configuration.ConfigurationManager.AppSettings["ConStr"];
            var decryptConStr = Encr2014.EncryptionModule.msDecryptTool2014(conStr, "msqJmbr21#");
            this.Database.Connection.ConnectionString = decryptConStr;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<tblDocSerial> tblDocSerials { get; set; }
        public virtual DbSet<tblMailEntry> tblMailEntries { get; set; }
    }
}
