//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMailEntry
    {
        public int EntryID { get; set; }
        public string EntryDateTime { get; set; }
        public int CustID { get; set; }
        public string AWBprefix { get; set; }
        public int AWBserial { get; set; }
        public string AWBNo { get; set; }
        public string AWBbarcode { get; set; }
        public string CustRef { get; set; }
        public string AccountNo { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public string CompanyName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string CityCode { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public string DeliveryArea { get; set; }
        public string EntryUser { get; set; } = "";
        public string ReceiveUser { get; set; } = "";
        public string ArrivalDateTime { get; set; } = "";
        public string SenderName { get; set; } = "";
        public string DispatchDateTime { get; set; } = "";
        public string Deliveryman { get; set; } = "";
        public string DeliveryDateTime { get; set; } = "";
        public string ReceiverName { get; set; } = "";
        public string ReceiverNumber { get; set; } = "";
        public decimal Charges { get; set; }
        public string DeliveryStatus { get; set; }
        public string LastUpdate { get; set; }
        public short SMSDone { get; set; }
        public string RecordSource { get; set; } = "";
        public short PrintedFlag { get; set; }
        public int ScheduleNo { get; set; }
        public string DeviceID { get; set; } = "";
        public string SignImage { get; set; } = "";
        public string Activities { get; set; }
        public string Remark { get; set; }
        public string SmallActivities { get; set; } = "";
        public short isUpload { get; set; }
        public string DestroyDate { get; set; } = "";
        public string DestroyBy { get; set; } = "";
        public string IdProof { get; set; } = "";
        public string ReceiverContact { get; set; } = "";
        public string DeliveryMode { get; set; } = "";
        public string Instructions { get; set; } = "";
        public short d1 { get; set; }
        public string DevID { get; set; } = "";
        public string ActualDeliveryTime { get; set; } = "";
        public string BrCode { get; set; } = "";
        public string IDType { get; set; } = "";
        public string IDNum { get; set; } = "";
        public string BrName { get; set; } = "";
        public string AuthName { get; set; }
        public string DocType { get; set; }
        public string Email { get; set; } = "";
        public string FrmChq { get; set; } = "";
        public string ToChq { get; set; } = "";
        public string DeliveryMethod { get; set; } = "";
        public string CIFno { get; set; } = "";
        public string PackType { get; set; } = "";
        public string CustPriority { get; set; } = "";
        public string BkType { get; set; } = "";
        public string Nol { get; set; } = "";
        public byte AWBPrinted { get; set; }
        public short NoS { get; set; }
        public string Nationality { get; set; } = "";
        public string UserModified { get; set; } = "";
        public string Street { get; set; } = "";
        public string Building { get; set; } = "";
        public int BatchNo { get; set; }
        public string ActivityStatus { get; set; }
        public string DlvFileDateTime { get; set; } = "";
        public string DlvBr { get; set; } = "";
        public string RecordData { get; set; } = "";
        public string Shipper { get; set; }
        public string JmbrRef { get; set; } = "";
        public string BookedBy { get; set; } = "";
        public string SenderContact { get; set; } = "";
        public byte BookingFlag { get; set; }
        public string EID_FullName { get; set; } = "";
        public string EID_Idnum { get; set; } = "";
        public string EID_IssueDate { get; set; } = "";
        public string EID_ExpiryDate { get; set; } = "";
        public string EID_Gender { get; set; } = "";
        public string EID_MStatus { get; set; } = "";
        public string EID_IdType { get; set; } = "";
        public string EID_Nationality { get; set; } = "";
        public string EID_Occupation { get; set; } = "";
        public string EID_SponsorName { get; set; } = "";
        public string ShipperAccNo { get; set; } = "";
        public string EID_DOB { get; set; } = "";
        public string Shipment_Type { get; set; } = "";
        public string Shipment_Location { get; set; } = "";
        public string Payment_Mode { get; set; } = "";
        public decimal Amount_Received { get; set; }
        public byte CashCollection { get; set; }
        public decimal CollectionAmount { get; set; }
        public byte CanFlag { get; set; }
        public string CanDateTime { get; set; } = "";
        public string CanBy { get; set; } = "";
        public string DeviceName { get; set; } = "";
        public string DevOnline { get; set; } = "";
        public string ExtraField1 { get; set; } = "";
        public string ExtraField2 { get; set; } = "";
        public string ExtraField3 { get; set; } = "";
        public string ExtraField4 { get; set; } = "";
        public string ExtraField5 { get; set; } = "";
        public string ContactDateTime { get; set; } = "";
        public string SpInstructions { get; set; } = "";
        public byte QenAccept { get; set; }
        public string FutureDate { get; set; } = "";
        public string ReturnService { get; set; } = "";
        public int DlvCount { get; set; }
        public short NoOfAttempts { get; set; }
        public string PromoCode { get; set; } = "";
        public string PromoCodeExpiry { get; set; } = "";
        public byte GoogleReview { get; set; }
        public string ReviewSMSDate { get; set; } = "";
    }
}
